// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.185
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInApp
{
    static class Vsix
    {
        public const string Id = "AE643C9F-EA6E-4A88-A122-34696D103F82";
        public const string Name = "Open in Altova XMLSpy";
        public const string Description = @"Open a file in Altova XMLSpy XML editor directly from Solution Explorer within Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0.22";
        public const string Author = "GregTrevellick";
        public const string Tags = "xml, xmlspy, altova, xsd, xslt, open, open in";
    }
}
